
[window]
opacity = 0.9
padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux"]

[font]

normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"

size = 14.0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
