[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv
# NODE_ENV = 'production'

[tools]
# specify single or multiple versions
awscli = '2.15.54'
rclone = '1.66.0'
serverless = "3.38.0"
bun = "latest"
node = "latest"
pnpm = "latest"
usage = "latest"
poetry = "latest"
gitconfig = "latest"
lazygit = "0.42.0"
