set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
call plug#begin('~/.vim/plugged')
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plug 'tpope/vim-fugitive'
Plug 'wikitopian/hardmode'
" Plug 'godlygeek/tabular'
Plug 'kien/ctrlp.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'cburroughs/pep8.py'
Plug 'scrooloose/syntastic'
Plug 'mhinz/vim-startify'
Plug 'tmhedberg/simpylfold'
Plug 'flazz/vim-colorschemes'
Plug 'posva/vim-vue'
"Plug 'tmux-plugins/vim-tmux'
"Plug 'majutsushi/tagbar'
"Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"Plug 'c0r73x/neotags.nvim'
"Plug 'editorconfig/editorconfig-vim'
Plug 'fatih/vim-go'
Plug 'leafgarland/typescript-vim'
Plug 'valloric/youcompleteme'

call plug#end()
filetype plugin indent on    " required

set runtimepath+=~/.vim_runtime

" Sets how many lines of history VIM has to remember
set history=500

" Enable filetype plugins
filetype plugin on
filetype indent on

" Set to auto read when a file is changed from the outside
set autoread

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

" Fast saving
nmap <leader>w :w!<cr>

" :W sudo saves the file 
" (useful for handling the permission-denied error)
command W w !sudo tee % > /dev/null

" Search mappings: These will make it so that going to the next one in a
" search will center on the line it's found in.
map N Nzz
map n nzz"

" Enable Airline extension by default
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'base16_monokai'
let g:airline#extensions#tabline#formatter = 'unique_tail'
" Case insensitive search
set ic

" Incremental search
set incsearch

" Highlight search
set hlsearch
""""""""""""""""""""""""""""""
"=> CTRL-P
""""""""""""""""""""""""""""""
let g:ctrlp_working_path_mode = 0
let g:ctrlp_map = '<c-f>'
map <leader>j :CtrlP<cr>
map <c-b> :CtrlPBuffer<cr>
let g:ctrlp_max_height = 20
let g:ctrlp_custom_ignore = 'node_modules\|^\.DS_Store\|^\.git\|^\.coffee'



let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }
:command Q q!
"Colorscheme - badwolf, with some tweaks
"set background=dark
syntax enable
"colorscheme BusyBee
colorscheme monokai
"colorscheme sol
let g:badwolf_darkgutter = 1
let g:badwolf_tabline = 2
let g:badwolf_css_props_highlight = 1
set pastetoggle=<F2>
                  " toggle paste mode
nmap <f3> :set number! number?<cr>
                  " toggle showing line numbers

" Search mappings: These will make it so that going to the next one in a
" search will center on the line it's found in.
map N Nzz
map n nzz
if has("autocmd")
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
endif

" Switch syntax highlighting on, when the terminal has colors
if &t_Co > 2 || has("gui_running")
  syntax on
endif

set termguicolors

" Set default file encoding to unicode
if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=utf-8,latin1
endif
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
nmap <f4> :tab all<cr>
"autocmd VimEnter,BufNewFile,BufReadPost * silent! call HardMode()
" set number
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

" Fold map
nnoremap <Space> za
vnoremap <Space> za

" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
set colorcolumn=120
nnoremap <leader>. :CtrlPTag<cr>
nnoremap <silent> <Leader>b :TagbarToggle<CR>
set clipboard=unnamed

set mouse-=a
nmap <F8> :TagbarToggle<CR>
" Use deoplete.
let g:deoplete#enable_at_startup = 1

set tags=./tags;

"neotags
set regexpengine=1
let g:neotags#cpp#order = 'ced'
let g:neotags#c#order = 'ced'
let g:neotags#python#order = 'mfc'


let g:python3_host_prog = '/usr/sbin/python'

