#!/bin/sh
lock() {
    i3lock -c 000000
    #i3lock -i ~/img/archlinux-simplygrey-left_bottom.png
    #i3lock -i ~/repos/dotfiles/i3/img/lock.png
    #i3lock -i  ~/Pictures/wallpaper.png
}
funlock() {
    i3lock -c 000000
    #i3lock -u -p win -i ~/repos/dotfiles/i3/img/lock.png
}
case "$1" in
    lock)
        lock
        ;;
    fun)
        funlock
        ;; 
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
